#!/bin/bash -e
# Evaluates python and scala notebooks and builds website

HERE=$(dirname "$(readlink -f "$0")")

OPTS="-j3"

if [ "${2^^}" = "EVAL" ]; then
    OPTS="$OPTS -D nbsphinx_execute=always"
fi

SPHINX="python3 -m sphinx $OPTS"

build_all() {
    $SPHINX "$HERE/." "$HERE/target/site"
}

if [ "${1^^}" = "ALL" ]; then
    build_all
elif [ "${1^^}" = "CLEAN" ]; then
    rm -r "$HERE/target"
else
    echo "Usage: $0 {all|clean} [eval]"
fi
